### ISSUE TITLE
逐字研读后，我想翻译为英文进行发表🤡

### ISSUE THREAD

**Issue by lif314** [ShiArthur03/ShiArthur03#108]

**Comment by Dongzhikang** [comment]
看来你是学到精髓了🤡

**Comment by douxy1994** [comment]
把所有点了 star 的列为 coauthors，不然告你学术不端🤣

**Comment by onefanwu** [comment]
作者写了英文版：https://github.com/ShiArthur03/ShiArthur03/blob/main/ShiBochenAcademicMisconduct.pdf
