### ISSUE TITLE
你不造假我不造假，一区论文发不出来，导师一作怎么来，怎么进步？怎么评长江？怎么评院士？🤣

### ISSUE THREAD

**Issue by Jordan-Haidee** [ShiArthur03/ShiArthur03#1510]

**Comment by rensushan** [comment]
人家施一公 颜宁也没有作假， 这不也都发了Nature Science.

**Comment by Jordan-Haidee** [comment]
这可不是我的想法，这是圈子里一些没实力还硬想往上爬的人为自己找的理由🙃


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月5日(周一) 下午4:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShiArthur03/ShiArthur03] 你不造假我不造假，一区论文发不出来，导师一作怎么来，怎么进步？怎么评长江？怎么评院士？🤣 (Issue #1510)




 
人家施一公 颜宁也没有作假， 这不也都发了Nature Science.
 
&mdash;
