### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Altria22-CPU** [ShiArthur03/ShiArthur03#1514]
很难有效，大家可以想一下实名举报为什么要“实名”。（抛开权势的干扰因素）
举一个例子：
我是某领导， 知道了施某的学术造假行为，但是消息来源是github，也查不到消息的来源，这个时候你会启动调查程序吗？因为消息没法证伪，程序不是你说启动就启动的，它是需要有基本的依据，最起码也要进行实名，因为如果是假的，举报人可能要承担责任。
github的举报说白了就是写小说，找不到源头，作者又不肯下场，没有太大的用处，引发不了任何行政或法律效力。
比如：人大的事件，就是典型案例，女方的实名举报行为，以自己可能会承担法律责任为代价进行举报，直接引发行政效力或法律效力，迫使相关机构启动调查程序，行政必须要结果要么严打被举报人，要么处理举报人，政府费了那么大力必须给个结果。
简单来说：
任何的举报都要以当事人可能需要承担一定的代价为标准才能启动，不承担任何代价不是举报是写小说，（即使是匿名举报也只是将你的信息隐藏而已）
这件事情这样下去，不会发生任何事情，一切照常进行，除非原作者亲自下场，直接在国内频道实名举报，虽然可能会被人整，吃一些苦头，但大概率最后会成功。但这就是举报。
有人说清华可能控评论了，我觉得甚至不用控，从表面上看这就是个fake news，没有任何有效的证据可以作证它， 有点政治意识的都会自觉忽视它。
虽然有点残忍：但是我认为作者也......→_→，你一点责任都不想承担就想让机关帮你办事你觉得可能吗？假如政府部门有人发善心，彻查此事，最后发现是假的，谁承担责任？你又不冒头，让帮你好心办事的人承担责任？
总结：想让有关机关彻查此事，最起码你要表现出诚意啊！出了问题查出来是假的帮有关部门背锅，清华哪边哪边大概也是确信作者不敢冒头，只要这件事没有搬到台面上，那就不是事情，就是个虚构的小说。
而且，这事情已经过去真么久了，对手早就做好准备了，看来作者还是没有被压榨到极限....又或者不在乎，或者是fakenews。

**Comment by Altria22-CPU** [comment]
作者这就是典型的拿人当枪使，出了问题一点责任不想承担。

**Comment by Altria22-CPU** [comment]
顺便说一下，当下最方便的举报就是直接实名身份证视频，除非对方只手通天能按死所有的视频，否则只要有一个视频流出，在社会产生影响，相关部门就必须启动调查程序，虽然最后的结果可能是“图片误用”，但是这样做至少可以把事情拉到台面上，至少确保程序的启动。
设想一下以一个机构/一群人为对手你台面上都斗不过人家，台面下能行？

**Comment by Altria22-CPU** [comment]
补充一下：
圣人的书不仅是用来读的，还真能用来办事，你不按书上的规矩出牌，还真就不行。(▼皿▼#)

**Comment by bbbccvbvv** [comment]
我觉得这个观点很小人。你不去辩驳举证的内容是否真实，而是对举证的手段提出质疑，典型的对人不对事，因为作者小心或者害怕，就否定这个人，污蔑作者人品，进而否定作者的全部，古代的清流手段玩的溜呀。你觉得内容有问题，贴出代码，贴出观点。我们都是普通人，如果作者有足够的背景扛得下所有后果，他为什么要怕？普通人收到了不公，借助第三方平台，为什么不敢用最正规的平台，他在怕什么？真正可以实现公平公正公开，老百姓为什么要怕？

**Comment by bbbccvbvv** [comment]
又发现了点有趣的，8月1日建的号，8月3号就发了这一个issue，莫不是水军？老施本人？

**Comment by Pvt-El** [comment]
> 补充一下： 圣人的书不仅是用来读的，还真能用来办事，你不按书上的规矩出牌，还真就不行。(▼皿▼#)

圣人书是用来反着读的，在洼地那么久还没活明白吗

**Comment by RHOWL3** [comment]
楼主是sbc团队派出来查作者身份的吧

**Comment by Tangent-90C** [comment]
想的太狭隘了，哪怕官方机构在程序上没法处理，作者目的也达到了，已经断了这水货的学术生涯了。

**Comment by rensushan** [comment]
如果能提供确凿的证据，匿名举报应该也可以吧。（联想到以前反腐反贪也允许匿名举报）
我估计问题出在如何拿到强力证据。
一个关键问题是：sbc的原始源代码库在哪？  这个git代码中给出的例子究竟是不是sbc的源代码？
至于他将之前毕业师兄的博士论文的第三章，直接翻译成英文这件事情，如果师兄作为当事人已经表示同意，这应该也没有问题。 这需要找师兄本人作证。

**Comment by Dou-Feng** [comment]
大家出不出头不知道，但我知道你肯定是不肯出头的了。

**Comment by Dou-Feng** [comment]
不出头在这里叫什么啊

**Comment by thu-zxs** [comment]
最烦你这种不是当事人强行代入别人长篇大论的，你想帮忙就想办法联系作者，给他出主意，比你在这逼逼赖赖要效率高很多

**Comment by thu-zxs** [comment]
<img width="1279" alt="屏幕快照 2024-08-09 下午8 40 05" src="https://github.com/user-attachments/assets/de970480-fe32-4731-9a57-fbdb6ead0c90">
看看，楼主是新号，国内水军那套学到精髓了

**Comment by Altria22-CPU** [comment]
所以，楼主出头了吗？这种人你觉得应该怎么帮他？事实上我们连信息的真实性都无法判断。

**Comment by Altria22-CPU** [comment]
匿名举报只是受到举报信息的机关会隐藏你的信息，github完全是国内的法外之地。国内很多举报机关进行举报时，首先需要做的就是验证你是否是中华人民共和国的公民，之后才能进入举报流程。
你在github举报，说极端点，你是否是中国人都有待考证。

**Comment by Altria22-CPU** [comment]
匿名举报只是受到举报信息的机关会隐藏你的信息，github完全是国内的法外之地。国内很多举报机关进行举报时，首先需要做的就是验证你是否是中华人民共和国的公民，之后才能进入举报流程。
你在github举报，说极端点，你是否是中国人都有待考证。

**Comment by Altria22-CPU** [comment]
> 我觉得这个观点太过于想当然。你不去辩驳举证的内容是否真实，而是对举证的手段提出质疑，典型的对人不对事，因为作者小心或者害怕，就否定这个人，污蔑作者人品，进而否定作者的全部，古代的清流手段玩的溜呀。你觉得内容有问题，贴出代码，贴出观点。我们都是普通人，如果作者有足够的背景扛得下所有后果，他为什么要怕？普通人收到了不公，借助第三方平台，为什么不敢用最正规的平台，他在怕什么？真正可以实现公平公正公开，老百姓为什么要怕？

你从一般人的道德来说确实没问题，但是举报实际上是一种政治权利行为，首先做的就是对人，之后对事，一个没有政治权利的人没有资格举报。
例如：楼主并非中国公民，那么他的所有举报无论正确与否都将归于无效。

**Comment by Altria22-CPU** [comment]
如果，此类举报能够成立的话，是不是随便一个人（不论他是什么人）都可以举报了，日本人、英国人、德国人等都可以对中国内的事情举报了，然后不论真假政府都要去调查。

**Comment by Altria22-CPU** [comment]
举报，不是一件大家相当然的事情，也不是靠单纯靠道德就能解决的问题，它是有一套完整的逻辑与流程的，需要多个人，多个部门的合作才能完成。而最起码的就是本人要出场。
反过来问？
大家为什么愿意相信一个法外之地的神秘人呢？
即使是阿桑奇人家也是带着真实身份登场的，就因为作者营造了一种被害者的氛围吗？
说句难听点：
        大家拿着他发的资料去帮他举报都不行，最根本的原因就是证据来源以及举报者本身都存在问题，就像你拿着一本圣经说这是我的地。
        正常人：你在国内被打了，你会去找美国法院帮你主持公道吗？我不知道大家看到这是什么想法，反过来问作者为什么不在国内举报？有人举报院长，有人举报税务局，到你这就.....

**Comment by Altria22-CPU** [comment]
最后的最后：
请楼主证明自己是一名中国人，
我们连作者是不是自己的同胞？是什么人？都无法确定就开始大谈特谈各种社会的黑暗、机构的腐败，合适吗？

**Comment by Dou-Feng** [comment]
经典不论对错只论心迹。如果举报者不是中国人，然后他所反应的情况属实（学术造假，且华清大学科研管理办法中已经指明学术造假是不合规行为），那么有关部门就不用去管了么？你觉得这个逻辑是通顺的么？作为管理者对实际问题一概不论，尽管反应情况属实，但是举报者是外国人或者非中国人民（我不知道我是否属于中国人民）就不予理会？

如果你觉得他反应的情况不属实，那就去质疑他的举报是否真实，你完全可以通过正确的方法，举证，而不是在这里民粹主义，以自己的意志代替大众的想法。你不出头不代表大家不会出头。

**Comment by Altria22-CPU** [comment]
> 经典不论对错只论心迹。如果举报者不是中国人，然后他所反应的情况属实（学术造假，且华清大学科研管理办法中已经指明学术造假是不合规行为），那么有关部门就不用去管了么？你觉得这个逻辑是通顺的么？作为管理者对实际问题一概不论，尽管反应情况属实，但是举报者是外国人或者非中国人民（我不知道我是否属于中国人民）就不予理会？
> 
> 如果你觉得他反应的情况不属实，那就去质疑他的举报是否真实，你完全可以通过正确的方法，举证，而不是在这里民粹主义，以自己的意志代替大众的想法。你不出头不代表大家不会出头。

政治不是靠道德来维系的，即使举报的内容属实，确实造假了，但是没有必要的前提。 
 程序就无法启动，如果在毫无根据的情况下，强行启动调查不就是滥用职权吗？例如：前苏联的秘密警察，最终将权力变成政治斗争的工具。
至于民粹，你没有发现你的想法更趋向于民粹吗？抛开各种事实与必要的程序不谈，为了迎合大家的想法而试图扭曲已经既定的规则程序。

**Comment by Altria22-CPU** [comment]
至于出头，你想过，如果一个正义的小伙伴帮他出手结果发现是假的，你有考虑到出手的人的后果吗？
那我问你凭什么好人要替作者承担责任？

**Comment by Altria22-CPU** [comment]
不论对错，只论心迹。法律权威，威不可测，大家都在遵守，凭啥你搞特权？
你为什么如此傲慢呢？相关机构每天面临的自己人正儿八经的举报都审不过来，你觉得就因为他举报的是清华就可以绕开必要的程序了吗？至于举报
一、举报者身份有问题，
二、缺乏真正强有力的证据，
如何帮他？

你以为外国人能举报，实际上外国人针对本国内部事务在国内根本不会传达到国家机关内，因为正经的举报首先是要核查你中国人的身份，你的假设本身都无法成立。

例如：你举报一下美国的特朗普试试看看人家会不会接受你发出的举报信？

举报商务局的哪个人不就是举报机构出错了，然后被打回来了，之后又重新举报的。
你有想过破坏既定规则的后果吗？假如权力机关可以随意的行使权力，是不是可以随意的用国家暴力对付人民了，规矩就是规矩，没有规矩不成方圆。
不遵守规矩就无法举报成功，破坏规矩的人就应该受到处罚，如果涉及比较机密的项目的话，作者的这种举报方式甚至涉嫌泄密。
现在是法治时代，不是我弱我有理，更不是我是被害人我有理，如果认为自己是对的请站在台面上拿出你的道理，只会堆在大家的背后是伪君子，真小人。
至于说机电权势大，翻手覆云的，他清华机电能有火箭军权势大，火箭军都能从头到脚清洗一遍，二十大后清理掉多少人大常委，哪一个比清华机电学院一把手差？整天谈一些阴谋论，结果上台面的证据一点拿不出……………
