### ISSUE TITLE
格局还是小了，怕是不知道私自链接境外互联网是什么罪哦

### ISSUE THREAD

**Issue by NealDeal34** [ShiArthur03/ShiArthur03#957]
为帝国主义攻击提供炮弹的，居心不良的，私生活糜烂的，有利可图的，人格扭曲的，受操控的，无聊的，哗众取宠的，多次发表不当言论的

**Comment by XSforAI** [comment]
笑死，你怕是不知道国内也可以访问吧，怎么盖这么大名头，你是本人还是利益相关啊，你是赵教授？

**Comment by Nipers** [comment]
> 笑死，你怕是不知道国内也可以访问吧，怎么盖这么大名头，你是本人还是利益相关啊，你是赵教授？

乐子人钓到鱼了

**Comment by wtdd** [comment]
俺直接百度点进来的呢~

**Comment by 1124562662** [comment]
说，你在倭寇王直那里当什么差？
不认识？待会儿你就认识了！

**Comment by debug3463** [comment]
> 笑死，你怕是不知道国内也可以访问吧，怎么盖这么大名头，你是本人还是利益相关啊，你是赵教授？

你这条小鱼,这么简单就被钓到吗? 看不出来是乐子人么?

**Comment by YuSakura000** [comment]
yysy，物理信道才算
